const fs = require('fs');
const path = require('path');

// Dossiers à analyser
const targetDirs = ['./src', './public', './pages', './components', './app'];

// Motifs de commentaires générés par l'IA à effacer
const aiPatterns = [
  /\/\/\s*Generated by.*/gi,
  /\/\/\s*AI-generated.*/gi,
  /\/\*[\s\S]*?Generated by[\s\S]*?\*\//gi,
  /\/\/\s*Helper function for.*/gi,
  /\/\/\s*TODO:\s*Implement.*/gi,
  /<!--[\s\S]*?Generated by[\s\S]*?-->/gi
];

function cleanFile(filePath) {
  if (!fs.existsSync(filePath)) return;
  let content = fs.readFileSync(filePath, 'utf8');
  let modified = false;

  aiPatterns.forEach((pattern) => {
    if (pattern.test(content)) {
      content = content.replace(pattern, '');
      modified = true;
    }
  });

  if (modified) {
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`🧹 Nettoyé : ${filePath}`);
  }
}

function scanDirectory(dir) {
  if (!fs.existsSync(dir)) return;
  const files = fs.readdirSync(dir);

  files.forEach((file) => {
    const fullPath = path.join(dir, file);
    if (fs.statSync(fullPath).isDirectory()) {
      if (file !== 'node_modules' && file !== '.git' && file !== '.next') {
        scanDirectory(fullPath);
      }
    } else if (/\.(js|jsx|ts|tsx|html|css|json)$/.test(file)) {
      cleanFile(fullPath);
    }
  });
}

console.log('🚀 Nettoyage des traces IA...');
targetDirs.forEach((dir) => scanDirectory(dir));
console.log('✅ Nettoyage terminé !');